# Generated by Django 4.2.14 on 2024-07-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_email_verified",
        ),
    ]
