# Generated by Django 4.2.14 on 2024-07-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
