# Generated by Django 4.2.14 on 2024-07-15 18:55

from django.db import migrations
import user_service.models


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0002_remove_user_is_email_verified"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user_service.models.UserManager()),
            ],
        ),
    ]
